apiVersion: v1
kind: Service
metadata:
  name: influx
spec:
  ports:
    - port: 8086
  selector:
    app: influx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
spec:
  progressDeadlineSeconds: 360
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: influx
      containers:
        - name: influx
          image: registry.nyan404.ru/telegraf-influxdb:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 600Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          env:
            - name: TELEGRAF_INPUT_URLS
              value: "https://next.vatsim-radar.com/api/data/vatsim/turns-data"
          ports:
            - containerPort: 8086
          volumeMounts:
            - name: influx-data
              mountPath: /var/lib/influxdb2
      volumes:
        - name: influx-data
          persistentVolumeClaim:
            claimName: radar-influx
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radar-influx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
