apiVersion: v1
kind: Service
metadata:
  name: influx-v2
spec:
  ports:
    - port: 8086
  selector:
    app: influx-v2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-v2
spec:
  progressDeadlineSeconds: 600
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: influx-v2
  template:
    metadata:
      labels:
        app: influx-v2
    spec:
      nodeSelector:
        doks.digitalocean.com/node-pool: influx-m
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: influx-v2
          image: ghcr.io/vatsim-radar/vatsim-radar/influx
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          resources:
            requests:
              cpu: 300m
              memory: 600Mi
            limits:
              cpu: 1700m
              memory: 1700Mi
          volumeMounts:
            - name: influx-data-v2
              mountPath: /root/.influxdbv2
      volumes:
        - name: influx-data-v2
          persistentVolumeClaim:
            claimName: radar-influx-v2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radar-influx-v2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
