services:
    frontend:
        build:
            context: .
            dockerfile: .config/dev.Dockerfile
        env_file:
            - ./.env
        container_name: vatsim-radar
        expose:
            - 8080
            - 9229
        command: /radar/.config/command.sh
        ports:
            - "8080:8080"
        volumes:
            - ".:/radar:rw"
        healthcheck:
            test: "bash -c 'echo -n > /dev/tcp/127.0.0.1/8080'"
            interval: 1s
            retries: 360
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started

    worker:
        build:
            context: .
            dockerfile: .config/dev.Dockerfile
        env_file:
            - ./.env
        container_name: vatsim-radar-worker
        command: /radar/.config/worker.sh
        ports:
            - 8880:8880
        volumes:
            - ".:/radar:rw"
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started
            frontend:
                condition: service_healthy

    vatglasses-worker:
        build:
            context: .
            dockerfile: .config/dev.Dockerfile
        env_file:
            - ./.env
        container_name: vatsim-radar-vg-worker
        command: /radar/.config/vatglasses-worker.sh
        volumes:
            - ".:/radar:rw"
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started
            frontend:
                condition: service_healthy

    db:
        image: mysql
        cap_add:
            - SYS_NICE
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=radar
            - MYSQL_ROOT_PASSWORD=localhost
        ports:
            - '3306:3306'
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
            timeout: 5s
            interval: 5s
            retries: 40
        volumes:
            - .config/db:/var/lib/mysql

    redis:
        image: redis
        command: redis-server /usr/local/etc/redis/redis.conf --requirepass RADAR
        expose:
            - 6379
        environment:
            - REDIS_APPLICATION_MODE=master
        volumes:
            - ./.config/redis.conf:/usr/local/etc/redis/redis.conf
