name: Feature Request / Feedback
description: Do you want us to improve or add something?
labels: [ "enhancement", "pending triage" ]
assignees: [ "daniluk4000" ]
type: "Feature"
body:
  - type: markdown
    attributes:
      value: |
        Hello! Thank you for suggesting an improvement for VATSIM Radar.
        
        Before reporting, please also check existing feature requests and enhancements in this repository - you can filter them by "feature request" label (also check closed ones).
        
        Also please check our roadmap - your request could already be planned to be implemented or is actually a separate feature.
  - type: input
    id: id
    attributes:
      label: Your Vatsim CID
      description: It is your Vatsim login. Required for us to contact you in Discord if you're there.
    validations:
      required: false
  - type: textarea
    id: what
    attributes:
      label: What do you suggest?
      description: Please tell us as much as possible about your suggestion
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why do you need that?
      description: Describe your request - why do you need that, how would it benefit to people, what are you trying to solve.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: If there are any alternatives, how can you deal with this problem today - or what other services already have it implemented?
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Is there something additional we need to know? Please tell us!
    validations:
      required: false
  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      description: Please validate your report
      options:
        - label: I have searched for other requests and didn't found any alike
          required: true
        - label: I have also checked roadmap, and this is not planned
          required: true
