name: Bug report (Next Branch)
description: Report found issue on Next branch
labels: [ "bug", "next", "pending triage" ]
assignees: ["daniluk4000"]
type: "Bug"
body:
  - type: markdown
    attributes:
      value: |
        Hello! This is a form for reporting an issue on https://next.vatsim-radar.com/ only. 
        
        Before reporting, please also check existing issues in this repository - you can filter them by "bug" and "next" labels (also check closed ones).
        
        Also check if you can reproduce on production (if yes - open issue there) and reported "next" versions.
        
        Also please check our roadmap - your "issue" could already be planned to be implemented or is actually a separate feature.
  - type: input
    id: id
    attributes:
      label: Your Vatsim CID
      description: It is your Vatsim login. Required for us to contact you in Discord, and also track your activity.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Radar version
      description: Please include Radar Next version - you can find it in the footer
      placeholder: For example, 0.1.1-alpha.1
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: Describe your issue
      description: Please tell us what's happening, what is expected and actual result. Include some screenshots and videos if there are some!
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: Reproduction steps
      description: Please describe how can we reproduce this issue - even if it's obvious. If your issue relates to some controller or specific user, include callsign(s) and cid(s). If it's hard to reproduce, a video would be nice to see.
    validations:
      required: true
  - type: input
    id: platform
    attributes:
      label: Platform
      description: Specify your platform (windows, macos, ios, android), as well as browser and it's version
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional info
      description: Is there something additional we need to know? Please tell us!
    validations:
      required: false
  - type: checkboxes
    id: validation
    attributes:
      label: Validation
      description: Please validate your report
      options:
        - label: I have searched for other issues and didn't found any alike
          required: true
        - label: I have also checked roadmap, and this is not planned
          required: true
        - label: I am QA or Patreon member and using next.vatsim-radar.com
          required: true
        - label: I couldn't reproduce it on production / it's issue in new functionality
          required: true
