// Airline logos are downloaded and preprocessed at build time into `public/logos/{CODE}.png`.
// The `airlineLogos` set (auto-imported, generated by `modules/airline-logos.ts`) contains
// every airline ICAO code that has a logo, so we never reference a missing file.

export function getAirlineLogoUrl(callsign?: string | null): string | null {
    if (!callsign) return null;

    const code = callsign.toUpperCase().match(/^([A-Z]{3})/)?.[1];
    if (!code || !airlineLogos.has(code)) return null;

    return `/logos/${ code }.png`;
}
