name: 'Codecheck'
description: 'Perform lint and build of project'

runs:
  using: composite
  steps:
    - name: Install deps
      shell: sh
      run: yarn install
    - name: Lint
      shell: sh
      run: yarn lint
    - name: Prisma
      shell: sh
      run: DATABASE_URL=mysql://root:localhost@db:3306/radar?schema=public npx prisma generate
    - name: Prepare
      shell: sh
      run: yarn prepare
    - name: Build package
      shell: sh
      run: yarn build
