services:
  frontend:
    build:
      context: .
      dockerfile: ../.config/dev.Dockerfile
    image: vr-1.1.1
    env_file:
      - ../.env.example
      - .env
    container_name: vatsim-radar
    volumes:
      - ${WORKSPACE_SOURCE:?}:${WORKSPACE_TARGET:?}
    expose:
      - 8080
      - 9229
    command: /radar/.config/command.sh
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9229:9229"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ../.config/dev.Dockerfile
    image: vr-1.1.1
    env_file:
      - ../.env.example
      - .env
    container_name: vatsim-radar-worker
    # command: sleep infinity
    command: /radar/.config/worker.sh
    ports:
      - 8880:8880
    volumes:
      - type: volume
        source: ${WORKSPACE_SOURCE:?}
        target: /radar
        volume:
          subpath: vatsim-radar 
    extra_hosts:
      - "host.docker.internal:host-gateway"


volumes:
  # $WORKSPACE_SOURCE is "devcontainer-volume" when the workspace is in a
  # volume, and devcontainer-volume is an alias for the actual external volume.
  # In bind-mount workspaces, it's an empty, unused volume created by compose.
  devcontainer-volume:
    name: ${WORKSPACE_CONTAINER_VOLUME_SOURCE:-not-used-in-bind-mount-workspace}
    external: ${WORKSPACE_IS_CONTAINER_VOLUME:?}
