import { getSettingValue, makeSettingsItems, setSettingByKey } from '~/composables/settings/v2/utils';

export const settingsItemVisibility = globalComputed(() => makeSettingsItems(({ notLoggedIn }) => ({
    atcFirs: {
        title: 'FIRs',
        searchKeywords: ['atc', 'artcc', 'center', 'uir', 'fss'],
        type: 'toggle',
        value: getSettingValue('map.visibility.atc.firs'),
        onChange: value => setSettingByKey('map.visibility.atc.firs', value),
    },
    atcApproach: {
        title: 'Approach',
        searchKeywords: ['atc', 'tracon', 'app'],
        type: 'toggle',
        value: getSettingValue('map.visibility.atc.approach'),
        onChange: value => setSettingByKey('map.visibility.atc.approach', value),
    },
    atcGround: {
        title: 'Locals',
        searchKeywords: ['atc', 'tower', 'ground', 'delivery', 'atis'],
        type: 'toggle',
        value: getSettingValue('map.visibility.atc.ground'),
        onChange: value => setSettingByKey('map.visibility.atc.ground', value),
    },
    atcLabels: {
        title: 'Approach Labels',
        searchKeywords: ['controllers', 'callsigns'],
        type: 'toggle',
        value: getSettingValue('map.visibility.atcLabels'),
        onChange: value => setSettingByKey('map.visibility.atcLabels', value),
    },
    vatglassesLabels: {
        title: 'VATGlasses labels Labels',
        searchKeywords: ['controllers', 'callsigns'],
        type: 'toggle',
        value: getSettingValue('map.visibility.vatglassesLabels'),
        onChange: value => setSettingByKey('map.visibility.vatglassesLabels', value),
    },
    artccTracons: {
        title: 'ARTCC TRACONs extensions',
        description: 'When disabled, you will still see extended ARTCCs and TRACONs (when initiated by APP, not CTR)',
        hint: 'Disables CTR extending APP behavior',
        searchKeywords: ['controllers', 'callsigns', 'duplicat', 'exten'],
        type: 'toggle',
        value: getSettingValue('map.visibility.artccTracons'),
        onChange: value => setSettingByKey('map.visibility.artccTracons', value),
    },
    airports: {
        title: 'Airports',
        type: 'toggle',
        value: getSettingValue('map.visibility.airports'),
        onChange: value => setSettingByKey('map.visibility.airports', value),
    },
    pilots: {
        title: 'Aircraft',
        searchKeywords: ['pilots', 'planes', 'traffic'],
        type: 'toggle',
        value: getSettingValue('map.visibility.pilots'),
        onChange: value => setSettingByKey('map.visibility.pilots', value),
    },
    gates: {
        title: 'Gates',
        type: 'toggle',
        value: getSettingValue('map.visibility.gates'),
        onChange: value => setSettingByKey('map.visibility.gates', value),
    },
    runways: {
        title: 'Runways',
        type: 'toggle',
        value: getSettingValue('map.visibility.runways'),
        onChange: value => setSettingByKey('map.visibility.runways', value),
    },
    pilotsInfo: {
        title: 'Show pilots info',
        searchKeywords: ['privacy', 'names', 'personal info'],
        type: 'toggle',
        value: getSettingValue('map.visibility.pilotsInfo'),
        onChange: value => setSettingByKey('map.visibility.pilotsInfo', value),
    },
    atcInfo: {
        title: 'Show controllers info',
        searchKeywords: ['privacy', 'names', 'personal info'],
        type: 'toggle',
        value: getSettingValue('map.visibility.atcInfo'),
        onChange: value => setSettingByKey('map.visibility.atcInfo', value),
    },
    pilotLabels: {
        title: 'Pilot labels',
        type: 'toggle',
        value: getSettingValue('map.visibility.pilotLabels'),
        onChange: value => setSettingByKey('map.visibility.pilotLabels', value),
        disabled: computed(() => !getSettingValue('map.visibility.pilots').value.value),
    },
})));
