---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-next
spec:
  progressDeadlineSeconds: 360
  replicas: 1
  selector:
    matchLabels:
      app: app-next
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: app-next
    spec:
      containers:
        - name: app-next
          image: ghcr.io/vatsim-radar/vatsim-radar/next
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
            limits:
              cpu: 950m
              memory: 950Mi
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 15
      imagePullSecrets:
        - name: ghcr-login-secret
      nodeSelector:
        doks.digitalocean.com/node-pool: premium-amd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-next
spec:
  progressDeadlineSeconds: 360
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: worker-next
  template:
    metadata:
      labels:
        app: worker-next
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      nodeSelector:
        doks.digitalocean.com/node-pool: premium-amd
      containers:
        - name: worker
          image: ghcr.io/vatsim-radar/vatsim-radar/next
          imagePullPolicy: Always
          command: ["/radar/.config/worker-prod.sh"]
          ports:
            - containerPort: 8880
          resources:
            requests:
              cpu: 300m
              memory: 300Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          readinessProbe:
            tcpSocket:
              port: 8880
            initialDelaySeconds: 5
            periodSeconds: 15
            successThreshold: 1
            failureThreshold: 10
            timeoutSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: worker-next
spec:
  ports:
    - port: 8880
  selector:
    app: worker-next
---
apiVersion: v1
kind: Service
metadata:
  name: app-next
spec:
  ports:
    - port: 3000
  selector:
    app: app-next
