name: Publish

on:
  push:
    branches: [ influx-v3]

jobs:
  push-influx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Add .env file
        run: |
          printf '%s\n' "${{ secrets.ENV }}" > .env
          printf '\nINFLUX_TOKEN=%s\n' "${{ secrets.INFLUX_TOKEN }}" >> .env
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          tags: ghcr.io/vatsim-radar/vatsim-radar/influx-v3:latest
          context: .
          push: true
          file: .config/influx.Dockerfile

  deploy-db-redis:
    runs-on: ubuntu-latest
    needs:
      - push-influx
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Set up kubectl
        uses: matootie/dokube@v1.4.1
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: main
      - name: Deploy Influx
        run: kubectl apply -f .config/k8s/influx.yml
      - name: Validate Influx
        run: kubectl rollout status deployment influx-v3
